# NODEJS Base
language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - npm i 
  - echo "Installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version 
  - docker build -t ms-backend-user .
  - docker tag ms-backend-user hiteshbn/ms-backend-user:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hiteshbn/ms-backend-user
